//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netriaEntities1 : DbContext
    {
        public netriaEntities1()
            : base("name=netriaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<juego> juego { get; set; }
        public virtual DbSet<musica> musica { get; set; }
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<respuesta> respuesta { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
