//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netriaEntities1 : DbContext
    {
        public netriaEntities1()
            : base("name=netriaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<juego> juego { get; set; }
        public virtual DbSet<musica> musica { get; set; }
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<respuesta> respuesta { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
