//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public juego()
        {
            this.pregunta = new HashSet<pregunta>();
            this.jugadores = new HashSet<user>();
        }
    
        public int idJuego { get; set; }
        public string User_loginnameUser { get; set; }
        public string tituloJuego { get; set; }
        public string descripcionJuego { get; set; }
        public Nullable<short> esPrivadoJuego { get; set; }
        public string coverJuego { get; set; }
        public int Musica_idMusica { get; set; }
        public Nullable<short> activadoJuego { get; set; }
    
        public virtual musica musica { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregunta> pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> jugadores { get; set; }
    }
}
