//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pregunta()
        {
            this.respuestas = new HashSet<respuesta>();
        }
    
        public int idPregunta { get; set; }
        public int Juego_idJuego { get; set; }
        public Nullable<int> segundosPregunta { get; set; }
        public Nullable<int> puntosPregunta { get; set; }
        public string contenidoPregunta { get; set; }
        public string tipoPregunta { get; set; }
        public string urlAyudaPregunta { get; set; }
    
        public virtual juego juego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuesta> respuestas { get; set; }
    }
}
