//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetRia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public respuesta()
        {
            this.user = new HashSet<user>();
        }
    
        public int idRespuesta { get; set; }
        public int Pregunta_idPregunta { get; set; }
        public string esCorrectoRespuesta { get; set; }
        public string contenidoRespuesta { get; set; }
    
        public virtual pregunta pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user { get; set; }
    }
}
