//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public juego()
        {
            this.preguntas = new HashSet<pregunta>();
            this.users = new HashSet<user>();
        }
    
        public int idJuego { get; set; }
        public string User_loginnameUser { get; set; }
        public string tituloJuego { get; set; }
        public string descripcionJuego { get; set; }
        public Nullable<short> esPrivadoJuego { get; set; }
        public string coverJuego { get; set; }
        public int Musica_idMusica { get; set; }
        public Nullable<short> activadoJuego { get; set; }
    
        public virtual musica musica { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregunta> preguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
