//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juego()
        {
            this.partidas = new HashSet<Partida>();
            this.preguntas = new HashSet<Pregunta>();
        }
    
        public int idJuego { get; set; }
        public string User_loginnameUser { get; set; }
        public string tituloJuego { get; set; }
        public string descripcionJuego { get; set; }
        public Nullable<short> esPrivadoJuego { get; set; }
        public string coverJuego { get; set; }
        public Nullable<int> Musica_idMusica { get; set; }
        public Nullable<short> activadoJuego { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> fechaJuego { get; set; }
    
        public virtual Musica musica { get; set; }
        public virtual User user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partida> partidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> preguntas { get; set; }
    }
}
