//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netriaEntities : DbContext
    {
        public netriaEntities()
            : base("name=netriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<juego> juegoes { get; set; }
        public virtual DbSet<musica> musicas { get; set; }
        public virtual DbSet<pregunta> preguntas { get; set; }
        public virtual DbSet<respuesta> respuestas { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
