//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netriaEntities : DbContext
    {
        public netriaEntities()
            : base("name=netriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musica> Musicas1 { get; set; }
        public virtual DbSet<Pregunta> Preguntas1 { get; set; }
        public virtual DbSet<User> Users1 { get; set; }
        public virtual DbSet<Juego> Juegoes1 { get; set; }
        public virtual DbSet<Partida> Partidas { get; set; }
        public virtual DbSet<Respuesta> Respuestas1 { get; set; }
    }
}
