//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pregunta()
        {
            this.respuestas = new HashSet<respuesta>();
        }
    
        public int idPregunta { get; set; }
        public int Juego_idJuego { get; set; }
        public Nullable<int> segundosPregunta { get; set; }
        public Nullable<int> puntosPregunta { get; set; }
        public string contenidoPregunta { get; set; }
        public string tipoPregunta { get; set; }
        public string urlAyudaPregunta { get; set; }
    
        public virtual juego juego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuesta> respuestas { get; set; }
    }
}
