-- MySQL Script generated by MySQL Workbench
-- Wed May 13 21:19:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `loginnameUser` VARCHAR(100) NOT NULL,
  `nickUser` VARCHAR(200) NULL,
  `passwordUser` VARCHAR(100) NULL,
  `fechaUser` DATETIME NULL,
  PRIMARY KEY (`loginnameUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Musica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Musica` (
  `idMusica` INT NOT NULL,
  `urlMusica` VARCHAR(200) NULL,
  PRIMARY KEY (`idMusica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Juego` (
  `idJuego` INT NOT NULL,
  `User_loginnameUser` VARCHAR(100) NOT NULL,
  `tituloJuego` VARCHAR(200) NULL,
  `descripcionJuego` VARCHAR(2000) NULL,
  `esPrivadoJuego` TINYINT NULL,
  `coverJuego` VARCHAR(500) NULL,
  `Musica_idMusica` INT NOT NULL,
  `activadoJuego` TINYINT NULL,
  PRIMARY KEY (`idJuego`),
  INDEX `fk_Juego_Musica1_idx` (`Musica_idMusica` ASC) VISIBLE,
  INDEX `fk_Juego_User1_idx` (`User_loginnameUser` ASC) VISIBLE,
  CONSTRAINT `fk_Juego_Musica1`
    FOREIGN KEY (`Musica_idMusica`)
    REFERENCES `mydb`.`Musica` (`idMusica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Juego_User1`
    FOREIGN KEY (`User_loginnameUser`)
    REFERENCES `mydb`.`User` (`loginnameUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jugo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jugo` (
  `Juego_idJuego` INT NOT NULL,
  `User_loginnameUser` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Juego_idJuego`, `User_loginnameUser`),
  INDEX `fk_Jugo_User1_idx` (`User_loginnameUser` ASC) VISIBLE,
  CONSTRAINT `fk_Jugo_Juego`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `mydb`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugo_User1`
    FOREIGN KEY (`User_loginnameUser`)
    REFERENCES `mydb`.`User` (`loginnameUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta` (
  `idPregunta` INT NOT NULL,
  `Juego_idJuego` INT NOT NULL,
  `segundosPregunta` INT(2) NULL,
  `puntosPregunta` INT(4) NULL,
  `contenidoPregunta` VARCHAR(200) NULL,
  `tipoPregunta` VARCHAR(10) NULL,
  `urlAyudaPregunta` VARCHAR(200) NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `fk_Pregunta_Juego1_idx` (`Juego_idJuego` ASC) VISIBLE,
  CONSTRAINT `fk_Pregunta_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `mydb`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respuesta` (
  `idRespuesta` INT NOT NULL,
  `Pregunta_idPregunta` INT NOT NULL,
  `esCorrectoRespuesta` VARCHAR(45) NULL,
  `contenidoRespuesta` VARCHAR(200) NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_Respuesta_Pregunta1_idx` (`Pregunta_idPregunta` ASC) VISIBLE,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`Pregunta_idPregunta`)
    REFERENCES `mydb`.`Pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respondio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respondio` (
  `User_loginnameUser` VARCHAR(100) NOT NULL,
  `Respuesta_idRespuesta` INT NOT NULL,
  PRIMARY KEY (`User_loginnameUser`, `Respuesta_idRespuesta`),
  INDEX `fk_Respondio_Respuesta1_idx` (`Respuesta_idRespuesta` ASC) VISIBLE,
  CONSTRAINT `fk_Respondio_User1`
    FOREIGN KEY (`User_loginnameUser`)
    REFERENCES `mydb`.`User` (`loginnameUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respondio_Respuesta1`
    FOREIGN KEY (`Respuesta_idRespuesta`)
    REFERENCES `mydb`.`Respuesta` (`idRespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
